const Stickers = Object.freeze({
  HI: "CAACAgIAAxkBAAEJl65nIhUkMwv2ri-ifbmyrjaxKcdCywAC2l8AAv4IEUnBOHBNsbbwkzYE",
  AGE: "CAACAgIAAxkBAAEJqN9nJMVj5mOyGcKgQ7QtNp-0gRMAAXkAAr1TAAKAFClJxNHpFK_k0Jc2BA",
  COURSE: "CAACAgIAAxkBAAEJqN5nJMVj-yxZ49TiM6EPuxE4_OPNYgACTmcAAgQIKEmYLNKtS0V39TYE",
  UNIVERSITY: "CAACAgIAAxkBAAEJqN1nJMVjc0cwKxQQeftOo7dylZwtiAACDVwAAhb8IUkUTie-g1iA0TYE",
  CITY: "CAACAgIAAxkBAAEJqOFnJMVjfPH6dZMfWCNpZ6HP7AqfQwACK1wAAiVaKUknOMO_ZxeURDYE",
  SPECIALITY: "CAACAgIAAxkBAAEJmKtnIinTcWslLgqfb90MI0nbrXrz9QAC2mcAAiGOEUlQAAEahyAG49w2BA",
  DATA: "CAACAgIAAxkBAAEJmKtnIinTcWslLgqfb90MI0nbrXrz9QAC2mcAAiGOEUlQAAEahyAG49w2BA",
  GREAT: "CAACAgIAAxkBAAEJqO5nJMXYhIuobbbTHsZnVghWDS0tvgACFFgAAiOrKUl3-LzcT897wzYE"
});

module.exports = Stickers;
