const Stickers = Object.freeze({
  HI: "CAACAgIAAxkBAAEJl65nIhUkMwv2ri-ifbmyrjaxKcdCywAC2l8AAv4IEUnBOHBNsbbwkzYE",
  AGE: "CAACAgIAAxkBAAEJmKtnIinTcWslLgqfb90MI0nbrXrz9QAC2mcAAiGOEUlQAAEahyAG49w2BA",
  COURSE: "CAACAgIAAxkBAAEJmKtnIinTcWslLgqfb90MI0nbrXrz9QAC2mcAAiGOEUlQAAEahyAG49w2BA",
  UNIVERSITY: "CAACAgIAAxkBAAEJmKtnIinTcWslLgqfb90MI0nbrXrz9QAC2mcAAiGOEUlQAAEahyAG49w2BA",
  CITY: "CAACAgIAAxkBAAEJmKtnIinTcWslLgqfb90MI0nbrXrz9QAC2mcAAiGOEUlQAAEahyAG49w2BA",
  SPECIALITY: "CAACAgIAAxkBAAEJmKtnIinTcWslLgqfb90MI0nbrXrz9QAC2mcAAiGOEUlQAAEahyAG49w2BA",
});

module.exports = Stickers;

